services:    
    Webkul\Magento2GroupProductBundle\EventListener\AkeneoVersionsCompatibility:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernalRequest }
            
    wk_commond_m2.group_product_event.listener:
        class:  'Webkul\Magento2GroupProductBundle\EventListener\AkeneoVersionsCompatibility'          
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
    
    wk_commond_m2.group_product_event.entity_modification.listener:
        class: Webkul\Magento2GroupProductBundle\EventListener\EntityModificationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2_group_product_connector_service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.pre_save, method: onPreSave }

    wk_commond_m2.group_product_event.entity_modification.listener_on_delete:
        class: Webkul\Magento2GroupProductBundle\EventListener\EntityModificationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2_group_product_connector_service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.pre_remove, method: onPreRemove }