extensions:
    # Attribute Mapping Model
    webkul-magento2-connector-data-mapping-create-modal:
        module: webkul/magento2/form/configuration/datamapping/modal
        config:
            labels:
                title: webkul_magento2_connector.entity.data_mapping.create_popin.title
                subTitle: webkul_magento2_connector.item.data_mapping
            picture: illustrations/Groups.svg
            successMessage: pim_enrich.entity.group_type.message.created
            editRoute: webkul_magento2_connector_configuration_data_mapping
            postUrl: webkul_magento2_connector_configuration_data_mapping_create

    # Mapping Type Field
    webkul-magento2-connector-type-create-form:
        module: webkul/magento2/form/configuration/datamapping/type
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: magento2EntityId
            label: webkul_magento2_connector.entity.data_mapping.create_popin.type
     
     # Akeneo Select Attribute Mapping Field
    webkul-magento2-connector-select-attribute-create-form:
        module: webkul/magento2/form/configuration/datamapping/attribute/akeneo
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 20
        config:
            identifier: akeneoEntityId
            label: webkul_magento2_connector.entity.data_mapping.create_popin.akeneoAttribute
    
    # Akeneo Attribute select
    webkul-magento2-connector-select-attribute-add-category:
        module: webkul/magento2/form/configuration/datamapping/attribute/select
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 30
        config:
            fieldName: addAttribute
            label: pim_enrich.entity.add_attribute.uppercase_label
            choiceRoute: webkul_magento2_connector_configuration_akeneo_attribute_get

    # Akeneo Category Mapping Field
    webkul-magento2-connector-select-category-create-form:
        module: webkul/magento2/form/configuration/datamapping/category/akeneo
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 40
        config:
            identifier: akeneoEntityId
            label: webkul_magento2_connector.entity.data_mapping.create_popin.akneoCategory
    
    # Akeneo Category select
    webkul-magento2-connector-select-category-add-category:
        module: webkul/magento2/form/configuration/datamapping/category/select
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 50
        config:
            fieldName: addCategory
            label: pim_enrich.entity.add_category.uppercase_label
            choiceRoute: webkul_magento2_connector_configuration_akeneo_category_get

    # Magento Attribute Mapping Field
    webkul-magento2-connector-magento2-attribute-create-form:
        module: webkul/magento2/form/configuration/datamapping/attribute/magento
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 60
        config:
            identifier: magento2EntityId
            label: webkul_magento2_connector.entity.data_mapping.create_popin.magento2Attribute
    
    # Magento Category Mapping Field
    webkul-magento2-connector-magento2-category-create-form:
        module: webkul/magento2/form/configuration/datamapping/category/magento
        parent: webkul-magento2-connector-data-mapping-create-modal
        targetZone: fields
        position: 70
        config:
            identifier: magento2EntityId
            label: webkul_magento2_connector.entity.data_mapping.create_popin.magento2Category