extensions:
    webkul-magento2-connector-data-mapping-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    webkul-magento2-connector-data-mapping-index-grid-container:
        module: pim/common/simple-view
        parent: webkul-magento2-connector-data-mapping-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    webkul-magento2-connector-data-mapping-index-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-magento2-connector-data-mapping-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    webkul-magento2-connector-data-mapping-index-grid-title:
        module: pim/common/grid-title
        parent: webkul-magento2-connector-data-mapping-index
        targetZone: title
        config:
            title: webkul_magento2_connector.data_mapping.index.title

    webkul-magento2-connector-data-mapping-index-filters-list:
        module: oro/datafilter/filters-list
        parent: webkul-magento2-connector-data-mapping-index-grid-container
        targetZone: filters

    webkul-magento2-connector-data-mapping-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: webkul-magento2-connector-data-mapping-index-grid-container
        targetZone: filters