parameters:
    hummingbird_xlsxconnector.array_converter.flat.product.class: 'Hummingbird\Bundle\XlsxConnectorBundle\ArrayConverter\FlatToStandard\Product'

services:
    hummingbird_xlsxconnector.array_converter.flat.product:
        class: '%hummingbird_xlsxconnector.array_converter.flat.product.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.field_converter'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_merger'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_mapper'
            - '@pim_connector.array_convertor.checker.fields_requirement'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.array_converter.flat_to_standard.product_value'