services:
    hummingbird_xlsx_connector.job.custom_xlsx_product_import:
            class: '%pim_connector.job.simple_job.class%'
            arguments:
                - 'hb_custom_xlsx_product_import'
                - '@event_dispatcher'
                - '@akeneo_batch.job_repository'
                -
                    - '@hummingbird_xlsx_connector.step.custom_xlsx_product_import.import'
            tags:
                - { name: akeneo_batch.job, connector: 'Hummingbird Xlsx Connector', type: '%pim_connector.job.import_type%' }