services:
    pim_enrich.event_listener.wk_bundle_product_association_product_picker_grid_before_listener:
        class: '%pim_datagrid.event_listener.configure_product_grid_listener.class%'
        arguments:
            - '@pim_datagrid.datagrid.configuration.product.context_configurator'
            - '@pim_datagrid.datagrid.configuration.product.columns_configurator'
            - '@pim_datagrid.datagrid.configuration.product.filters_configurator'
            - '@pim_datagrid.datagrid.configuration.product.sorters_configurator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.before.wk-bundle-product-association-product-picker-grid, method: buildBefore }
    
    pim_enrich.event_listener.wk_bundle_product_association_product_picker_grid_after_listener:
        class: '%pim_datagrid.event_listener.add_parameters_to_product_grid.class%'
        arguments:
          - [dataLocale]
          - '@oro_datagrid.datagrid.request_params'
          - '@pim_catalog.context.catalog'
          - '@pim_user.context.user'
          - false
          - '@request_stack'
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.wk-bundle-product-association-product-picker-grid, method: onBuildAfter }