services:
    webkul.step.magento2_product_association_export:
        class: '%webkul_magento2.export.step%'       
        arguments:
            - 'product_association_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@pim_connector.reader.database.product' 
            - '@webkul_magento2.processor.magento_normalization.product.association'
            - '@webkul_magento2.writer.product.association.api'
            - 10
    
    webkul.step.magento2_product_model_association_export:
        class: '%webkul_magento2.export.step%'       
        arguments:
            - 'product_model_association_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@pim_connector.reader.database.product_model' 
            - '@webkul_magento2.processor.magento_normalization.product_model.association'
            - '@webkul_magento2.writer.product.association.api'
            - 10

    webkul.step.magento2_product_association_quick_export:
        class: '%webkul_magento2.export.step%'       
        arguments:
            - 'product_association_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@pim_enrich.reader.database.product'
            - '@webkul_magento2.processor.magento_normalization.product.association'
            - '@webkul_magento2.writer.product.association.api'
            - 10
    
    webkul.step.magento2_product_model_association_quick_export:
        class: '%webkul_magento2.export.step%'     
        arguments:
            - 'product_model_association_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@pim_enrich.reader.database.product_model'
            - '@webkul_magento2.processor.magento_normalization.product_model.association'
            - '@webkul_magento2.writer.product.association.api'
            - 10