extensions:
    wk_magento2_akeneo-product-model-completeness-filter:
        module: magento2/filter/product-model/completeness
        config:
            neverEmpty: false
            operators:
                - ALL
                - AT LEAST COMPLETE
                - ALL COMPLETE
            
    wk_magento2_akeneo-product-completeness-filter:
        module: magento2/filter/product/completeness
        config:
            neverEmpty: true
            operators:
                - GREATER OR EQUALS THAN ON AT LEAST ONE LOCALE
                - ALL
                - GREATER OR EQUALS THAN ON ALL LOCALES
                - LOWER THAN ON ALL LOCALES

    wk_magento2_akeneo-attribute-identifier-filter:
        module: magento2/filter/attribute/identifier