Webkul\ImageGalleryBundle\Entity\Gallery:
    type: entity
    table: wk_product_gallery
    repositoryClass: Webkul\ImageGalleryBundle\Repository\GalleryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        medias:
            targetEntity: Webkul\ImageGalleryBundle\Entity\GalleryMedia
            mappedBy: gallery
            cascade:
                - persist
                - remove   
    manyToMany:
        tags:
            targetEntity: Webkul\ImageGalleryBundle\Entity\GalleryTag
            inversedBy: gallery
            cascade:
                - refresh
            joinTable:
                name: wk_product_gallery_gallery_tag
                joinColumns:
                    gallery_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    tag_id:
                        referencedColumnName: id 

    fields:
        code:
            type: string
            length: 255
            unique: true
        starred:
            type: boolean
            options:
                default: false
            nullable: true
        description:
            type: text
            nullable: true
        title:
            type: string
            length: 255
            nullable: true
        alt:
            type: string
            length: 255
            nullable: true
        animationType:
            type: string
            length: 255
            nullable: true
        galleryGroup:
            type: string
            length: 255
            nullable: true
        expiration_date:
            type: string
            length: 255
            nullable: true    
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    lifecycleCallbacks: 
        prePersist: [ setCreatedAtValue, setUpdatedAtValue ]
        postUpdate: [ setUpdatedAtValue ]