Webkul\ImageGalleryBundle\Entity\GalleryMedia:
    type: entity
    table: wk_product_gallery_media
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        filePath:
            type: string
            length: 255
            unique: true
        originalFilename:
            type: string
            length: 255   
        description:
            type: text
            nullable: true
        thumbnail:
            type: boolean
            options:
                default: false
            nullable: true
        title:
            type: string
            length: 255
            nullable: true       
    manyToOne:
        gallery:
            targetEntity: Webkul\ImageGalleryBundle\Entity\Gallery
            inversedBy: medias
            join_column:
                name: gallery_id
                referencedColumnName: id
                onDelete: cascade