Webkul\ImageGalleryBundle\Entity\Group:
    type: entity
    table: wk_gallery_group
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
