extensions:
    #  group product
    pim-product-index-create-button:
        module: pim/form/common/product/create-button
        parent: pim-product-index
        targetZone: buttons
        config:
            buttonTitle: pim_enrich.entity.product.create
            modalTitle: pim_enrich.entity.product.modalTitle
            subTitle: pim_enrich.entity.product.subTitle
            choices:
                create-bundle-product:
                    form: pim-product-create-modal-bundle
                    title: Bundle Product
                    icon: icon-product
                    aclResourceId: pim_enrich_product_create

    # simple product
    pim-product-create-modal:
       module: pim/form/common/creation/modal
       config:
           labels:
               title: pim_enrich.entity.product.create_popin.title
               subTitle: pim_menu.tab.products
           picture: illustrations/Product.svg
           successMessage: pim_enrich.entity.product.message.created
           editRoute: pim_enrich_product_edit
           postUrl: webkul_magento2_connector_product_rest_create

    pim-product-create-sku:
        module: pim/product-edit-form/creation/identifier
        parent: pim-product-create-modal
        targetZone: fields
        position: 10
        config:
            identifier: identifier

    pim-product-create-family:
        module: pim/form/common/fields/simple-select-async
        parent: pim-product-create-modal
        targetZone: fields
        position: 20
        config:
            fieldName: family
            label: pim_enrich.entity.product.meta.family.title
            choiceRoute: pim_enrich_family_rest_index
            
    # bundle product 
    pim-product-create-modal-bundle:
       module: pim/form/common/creation/modal
       config:
           labels:
               title: pim_enrich.entity.product.create_popin.title
               subTitle: pim_menu.tab.products
           picture: illustrations/Product.svg
           successMessage: pim_enrich.entity.product.message.created
           editRoute: pim_enrich_product_edit
           postUrl: webkul_magento2_connector_product_bundle_rest_create

    pim-product-bundle-create-sku:
        module: pim/product-edit-form/creation/identifier
        parent: pim-product-create-modal-bundle
        targetZone: fields
        position: 10
        config:
            identifier: identifier

    pim-product-bundle-create-family:
        module: pim/form/common/fields/simple-select-async
        parent: pim-product-create-modal-bundle
        targetZone: fields
        position: 20
        config:
            fieldName: family
            label: pim_enrich.entity.product.meta.family.title
            choiceRoute: pim_enrich_family_rest_index