extensions:
    wk_bundle_associations-product-picker-form:
        module: pim/product-edit-form/product-and-product-model-picker
        config:
            datagridName: wk-bundle-product-association-product-picker-grid
            description: pim_enrich.form.product.tab.associations.manage_description
            categoryTreeRoute: pim_enrich_categorytree
            columnName: identifier
            fetcher: product

    association-product-picker-form-filters-list:
        module: oro/datafilter/filters-list
        parent: wk_bundle_associations-product-picker-form
        targetZone: filters

    association-product-picker-form-filters-manage:
        module: oro/datafilter/filters-button
        parent: association-product-picker-form-filters-list
        config:
            displayAsPanel: true