attribute_fields:
    pim_catalog_gallery_group: webkulgallery/asset-field

extensions:
    webkulgallery-product-media-select-form:
        module: webkulgallery/select/item-picker
        config:
            datagridName: webkul-gallery-media-select-grid
            title: webkulgallery.product_media.title
            description: webkulgallery.product_media.description
            categoryTreeRoute: webkul_gallery_categorytree
            columnName: code
            fetcher: gallery

    webkulgallery-product-media-select-form-filters-list:
        module: oro/datafilter/filters-list
        parent: webkulgallery-product-media-select-form
        targetZone: filters

    webkulgallery-product-media-select-form-filters-manage:
        module: oro/datafilter/filters-button
        parent: webkulgallery-product-media-select-form
        targetZone: filters

    # webkulgallery-product-media-image-slider-form:
    #     module: webkulgallery/select/image-gallery-slider
        # config:
        #     datagridName: webkul-gallery-media-select-grid
        #     title: webkulgallery.product_media.title
        #     description: webkulgallery.product_media.description
        #     categoryTreeRoute: webkul_gallery_categorytree
        #     columnName: code
        #     fetcher: gallery