extensions:
    # menu item
    pim-menu-webkul-gallery:
        module: pim/menu/tab
        parent: pim-menu
        position: 100
        targetZone: mainMenu
        aclResourceId: image_gallery_configuration
        config:
            title: Akeneo Image Gallery
            iconModifier: iconWebkulGallery
            to: webkul_akeneo_gallery_index

    pim-webkul-gallery-index:
        module: pim/common/simple-view
        config:
            template: pim/template/common/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    pim-webkul-gallery-index-grid-container:
        module: pim/common/simple-view
        parent: pim-webkul-gallery-index
        targetZone: content
        config:
            # template: pim/template/form/index/index
            template: pim/template/product/index
            templateParams:
                gridName: webkul-gallery-grid

    pim-webkul-gallery-index-user-navigation:
        module: pim/menu/user-navigation
        parent: pim-webkul-gallery-index
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    pim-webkul-gallery-index-grid-title:
        module: pim/common/grid-title
        parent: pim-webkul-gallery-index
        targetZone: title
        config:
            title: pim_enrich.index.gallery.title

    pim-webkul-gallery-index-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-webkul-gallery-index
        targetZone: breadcrumbs
        config:
            tab: pim-menu-webkul-gallery


    pim-webkul-gallery-index-grid:
        module: pim/grid/table
        parent: pim-webkul-gallery-index-grid-container
        targetZone: grid
        config:
            gridName: webkul-gallery-grid
            datagridLoadUrl: pim_datagrid_load    

    pim-webkul-gallery-index-pagination:
        module: oro/datagrid/pagination-input
        parent: pim-webkul-gallery-index-grid-container
        targetZone: toolbar
        config:
            gridName: webkul-gallery-grid

    pim-webkul-gallery-index-display-selector:
        module: pim/datagrid/display-selector
        parent: pim-webkul-gallery-index
        targetZone: search
        position: 20
        config:
            gridName: webkul-gallery-grid

    pim-webkul-gallery-index-create-version:
        module: webkulgallery/form/common/index/version
        parent: pim-webkul-gallery-index
        targetZone: bottom-panel
        position: 110
        aclResourceId: image_gallery_configuration

    pim-webkul-gallery-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-webkul-gallery-index
        targetZone: buttons
        position: 100
        aclResourceId: image_gallery_configuration
        config:
           iconName:  plus
           title:     webkul-gallery-grid.index.create_btn
           modalForm: webkul-gallery-create-modal

    pim-webkul-gallery-index-create-group-button:
        module: webkulgallery/form/common/index/create-button
        parent: pim-webkul-gallery-index
        targetZone: buttons
        position: 90
        aclResourceId: image_gallery_configuration
        # config:
        #    iconName:  plus
        #    title:     webkul-gallery-grid.index.create_group_btn  
        #    modalForm: webkul-gallery-create-modal

        #    url: webkulgallery_group_data_grid
        # config:
        #     alias:  webkul-group-export-mapping-grid


    pim-webkul-gallery-index-left-column:
        module: pim/form/common/column
        parent: pim-webkul-gallery-index
        targetZone: column
        config:
          stateCode: gallery_media
          navigationTitle: pim_enrich.entity.asset.navigation
          
    pim-webkul-gallery-index-column-inner:
        module: pim/common/simple-view
        parent: pim-webkul-gallery-index-left-column
        targetZone: navigation
        config:
          template: pim/template/product/grid/column-inner

    pim-webkul-gallery-index-grid-filters-manage:
        module: oro/datafilter/filters-button
        parent: pim-webkul-gallery-index-column-inner
        targetZone: manage-filters-button
        
    pim-webkul-gallery-index-grid-filters-list:
        module: oro/datafilter/filters-list
        parent: pim-webkul-gallery-index-column-inner
        targetZone: filters
        config:
            displayedAsColumn: true
        
    pim-webkul-gallery-index-mass-actions:
        module: pim/grid/mass-actions
        parent: pim-webkul-gallery-index
        targetZone: bottom-panel
        config:
            label: webkul-gallery.asset.selected

    pim-webkul-gallery-index-actions-panel:
        module: oro/datagrid/actions-panel
        parent: pim-webkul-gallery-index-mass-actions
        targetZone: actions-panel
