datagrid:
    webkul-gallery-media-select-grid:
        options:
            entityHint: imageGallery
            manageFilters: false
            requireJSModules:
                - webkulgallery/datagrid/column-form-listener
            columnListener:
                dataField: code
                columnName: is_checked
            routerEnabled: false
        source:
            acl_resource: image_gallery_configuration
            type: webkul_gallery_datasource
            entity: 'Webkul\ImageGalleryBundle\Entity\Gallery'
            query:
                select:
                    - wem.id
                    - wem.code
                from:
                    - { table: 'Webkul\ImageGalleryBundle\Entity\Gallery', alias: wem }
        columns:
            is_checked:
                frontend_type: gallery-boolean
                data_name:     is_checked
                editable:      true
            thumbnail:
                label:  Thumbnail
                frontend_type: gallery-thumbnail
            code:
                type:          field
                frontend_type: string
                label:         Code            
            createdAt:
                type:          date_with_user_timezone
                frontend_type: date
                label:         Created At
            updatedAt:
                type:          date_with_user_timezone
                frontend_type: date
                label:         Updated At
        properties:
            id: ~
            code: ~
        sorters:
            columns:
                code:
                    data_name: wem.code                
            default:
                id: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC'
        filters:
            columns:
                code:
                    type:      search
                    label:     Code of Gallery
                    data_name: wem.code                
                createdAt:
                    type:      date
                    data_name: wem.createdAt
                updatedAt:
                    type:      date
                    data_name: wem.updatedAt                


