datagrid:
    webkul-gallery-grid:
        options:
            entityHint: imageGallery
            displayTypes:
                default:
                    label: grid.display_selector.list
                gallery: # just like product view
                    label: grid.display_selector.gallery
                    rowView: webkulgallery/datagrid/row/asset
                    manageColumns: false
        source:
            acl_resource: image_gallery_configuration
            type: webkul_gallery_datasource
            entity: 'Webkul\ImageGalleryBundle\Entity\Gallery'
            query:
                select:
                    - wem.id
                    - wem.code
                from:
                    - { table: 'Webkul\ImageGalleryBundle\Entity\Gallery', alias: wem }
        columns:
            code:
                label:  Code
                frontend_type: label
            thumbnail:
                label:         Thumbnail
                frontend_type: gallery-thumbnail   
            description:
                type:          field
                frontend_type: string
                label:         Description
        
            createdAt:
                label:         Created At
                frontend_type: date
                type:          date_with_user_timezone
            updatedAt:
                label:         Updated At
                frontend_type: date
                type:          date_with_user_timezone       
            starred:
                label:  Favourites
                frontend_type: webkulgallery-asset-star
     
        properties:
            id: ~
            edit_link:
                type: url
                route: webkul_gallery_asset_edit
                params:
                    - code
            delete_link:
                type: url
                route: webkul_gallery_asset_delete
                params:
                    - code
        actions:
        # uncomment start
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         Delete
                link:          delete_link
                acl_resource:  image_gallery_configuration
        # uncomment end
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit
                tab:       pim_product_asset_properties
                link:      edit_link
                rowAction: true           
                acl_resource:  image_gallery_configuration

        sorters:
            columns:
                code:
                    data_name: wem.code
                createdAt:
                    data_name: wem.createdAt   
                updatedAt:
                    data_name: wem.updatedAt            
                # starred: 
                #     data_name: wem.starred
        filters:
            columns:
                code:
                    type:      search
                    label:     Code of Gallery
                    data_name: wem.code                
                createdAt:
                    type:      date
                    data_name: wem.createdAt
                updatedAt:
                    type:      date
                    data_name: wem.updatedAt    
                starred:
                    type:      boolean
                    data_name: wem.starred
                description:
                    type:      string
                    label:     Description
                    data_name: wem.description
                galleryGroup:
                    type:      choice
                    label:     Groups
                    data_name: wem.galleryGroup
                    options:
                        field_options:
                            multiple: true
                            choices:  '@webkul.image.gallery.connector.service->getAllGroups'