datagrid:
    webkul-gallery-group-grid:
        options:
            entityHint: group
        source:
            acl_resource: image_gallery_configuration
            type: webkul_gallery_group_datasource
            entity: 'Webkul\ImageGalleryBundle\Entity\Group'
            query:
                select:
                    - wem.id
                    - wem.code
                from:
                    - { table: 'Webkul\ImageGalleryBundle\Entity\Group', alias: wem }
        columns:
            code:
                label:  Code
                frontend_type: label
     
        properties:
            id: ~
            delete_link:
                type: url
                route: webkul_gallery_group_delete
                params:
                    - id
        actions:
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         Delete
                link:          delete_link
                acl_resource:  image_gallery_configuration

        sorters:
            columns:
                code:
                    data_name: wem.code
        filters:
            columns:
                code:
                    type:      search
                    label:     Code of Group
                    data_name: wem.code