datagrid:
    product-grid:
        mass_actions:
            quick_export_grid_context_connector: 
                type: export
                label: pim.grid.mass_action.quick_export.connector
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:                   
                    _format: csv
                    _contentType: text/csv
                    _jobCode: csv_product_grid_context_quick_export
                    _displayedColumnsOnly: 1
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            quick_export_connector: 
                type: export
                label: pim.grid.mass_action.quick_export.connector
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:                   
                    _format: csv
                    _contentType: text/csv
                    _jobCode: csv_product_grid_context_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            