parameters:
    webkul_gallery.datasource.class: Webkul\ImageGalleryBundle\Datasource\ImageGalleryDatasource
    webkul_gallery.datasource.result_record.hydrator.default.class: Webkul\ImageGalleryBundle\Datasource\Orm\ResultRecordHydrator
    webkul_gallery_group.datasource.class: Webkul\ImageGalleryBundle\Datasource\Orm\GroupDatasource
services:    
    webkul_gallery_module_connector_datagrid.datasource.mapping:
        class: '%webkul_gallery.datasource.class%'
        arguments:
            - '@webkul_gallery.repository.media'
            - '@webkul_gallery.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: webkul_gallery_datasource }
            
    webkul_gallery_module_group_connector_datagrid.datasource.mapping:
        class: '%webkul_gallery_group.datasource.class%'
        arguments:
            - '@webkul_gallery.repository.group'
            - '@pim_datagrid.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: webkul_gallery_group_datasource }

    webkul_gallery.datasource.result_record.hydrator.default:
        class: '%webkul_gallery.datasource.result_record.hydrator.default.class%'