services:
    Webkul\ImageGalleryBundle\Listener\ClassDefinationForCompatibility:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    
    wk_image_gallery.commond_event.listener:  
        class:  'Webkul\ImageGalleryBundle\Listener\ClassDefinationForCompatibility'          
        tags:
            - { name: kernel.event_listener, event: console.command, method: createUserSystem }
                