parameters:
    webkul_gallery.factory.asset: Webkul\ImageGalleryBundle\Entity\Gallery
    webkul_gallery.factory.asset_value.class: Webkul\ImageGalleryBundle\Factory\GalleryMediaValueFactory
    # webkulgallery.entity.value.class: Webkul\ImageGalleryBundle\Model\GalleryMediaValue

services:
    webkulgallery_attribute.factory.value.column_value:
        class: '%webkul_gallery.factory.asset_value.class%'
        public: false
        arguments:
            - '%webkulgallery.entity.value.class%'
            - 'pim_catalog_gallery_group'
        tags:
            - { name: pim_catalog.factory.value }

    webkul_gallery.factory.asset:
        class: '%akeneo_storage_utils.factory.simple.class%'
        arguments:
            - '%webkul_gallery.entity.image.class%'

