services:
    webkulgallery.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                csv_gallery_import: pim-job-instance-csv-base-import
                csv_gallery_export: pim-job-instance-csv-base-export

        tags:
            - { name: pim_enrich.provider.form, priority: 100 }
