parameters:

services:
    webkulgallery.job.job_parameters.constraint_collection_provider.simple_csv_export:
        class: '%pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_export.class%'
        arguments:
            -
                - 'csv_gallery_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    webkulgallery.job.job_parameters.default_values_provider.simple_csv_export:
        class: '%pim_connector.job.job_parameters.default_values_provider.simple_csv_export.class%'
        arguments:
            -
                - 'csv_gallery_export'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }

    webkulgallery.job.job_parameters.constraint_collection_provider.simple_csv_import:
        class: '%pim_connector.job.job_parameters.constraint_collection_provider.simple_csv_import.class%'
        arguments:
            -
                - 'csv_gallery_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }

    webkulgallery.job.job_parameters.default_values_provider.simple_csv_import:
        class: '%pim_connector.job.job_parameters.default_values_provider.simple_csv_import.class%'
        arguments:
            -
                - 'csv_gallery_import'
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }