parameters:
    webkulgallery.job_name.csv_gallery_import: csv_gallery_import
    webkulgallery.job_name.csv_gallery_export: csv_gallery_export
    webkulgallery.connector_name.csv_gallery_export: Akeneo Image Gallery
    
services:
    webkulgallery.job.gallery_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkulgallery.job_name.csv_gallery_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@pim_connector.step.charset_validator'
                - '@webkulgallery.step.csv_gallery.import'
            - true
        tags:
            - { name: akeneo_batch.job, connector: '%webkulgallery.connector_name.csv_gallery_export%', type: '%pim_connector.job.import_type%' }

    
    webkulgallery.job.gallery_export:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkulgallery.job_name.csv_gallery_export%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkulgallery.step.csv_gallery.export'
            - true
        tags:
            - { name: akeneo_batch.job, connector: '%webkulgallery.connector_name.csv_gallery_export%', type: '%pim_connector.job.export_type%' }

