services:    
    webkulgallery.processor.normalization.gallery:
        class: '%pim_connector.processor.normalization.class%'
        arguments:
            - '@webkulgallery.normalizer.standard.gallery'
            - '@akeneo_storage_utils.doctrine.object_detacher'

    webkulgallery.processor.denormalization.gallery:
        class: '%pim_connector.processor.denormalization.class%'
        arguments:
            - '@webkul_gallery.repository.media'
            - '@webkul_gallery.factory.asset'
            - '@webkul_gallery.updater.media'
            - '@validator'
            - '@akeneo_storage_utils.doctrine.object_detacher'