parameters:
    webkul_gallery.repository.image.class: Webkul\ImageGalleryBundle\Repository\GalleryRepository
    webkul_gallery.entity.image.class: Webkul\ImageGalleryBundle\Entity\Gallery
    webkul_gallery.repository.image_gallery.class: Webkul\ImageGalleryBundle\Repository\GalleryMediaRepository
    webkul_gallery.entity.image_gallery.class: Webkul\ImageGalleryBundle\Entity\GalleryMedia
    webkul_gallery.entity.group.class: Webkul\ImageGalleryBundle\Entity\Group
    webkul_gallery.repository.group.class: Webkul\ImageGalleryBundle\Repository\GroupRepository
services:    
    webkul_gallery.repository.media:
        public: true
        class: '%webkul_gallery.repository.image.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%webkul_gallery.entity.image.class%'

    webkul_gallery.repository.media_gallery:
        public: true
        class: '%webkul_gallery.repository.image_gallery.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%webkul_gallery.entity.image_gallery.class%'

    webkul_gallery.repository.group:
        public: true
        class: '%webkul_gallery.repository.group.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%webkul_gallery.entity.group.class%'