webkul_akeneo_gallery_index:
    path: /webkul/gallery/

webkul_gallery_configuration_get:
    path: /webkul/gallery/get
    defaults: { _controller: webkul.image_gallery_configuration.controller:getAction }
    methods: [GET]

#     webkul_gallery_asset_create:
#     path: /webkul/gallery/create
#     defaults: { _controller: webkul.image_gallery_configuration.controller:createAction }
#     methods: [POST]

webkul_gallery_asset_create_rest:
    path: /webkul/gallery/create/rest
    defaults: { _controller: webkul.image_gallery_configuration.controller:saveAction }
    methods: [POST]  

webkul_gallery_group_create_rest:
    path: /webkul/gallery/create/group
    defaults: { _controller: webkul.image_gallery_configuration.controller:saveGroupAction }
    methods: [POST]  
webkul_gallery_asset_media_create_rest:
    path: /webkul/gallery/media/create/rest 
    defaults: { _controller: webkul.image_gallery_configuration.controller:saveMediaAction }
    methods: [POST] 

webkul_gallery_rest_get:
    path: /webkul/gallery/{identifier}/rest
    defaults: { _controller: webkul.image_gallery_configuration.controller:getGalleryAction }
    methods: [GET]

webkulgallery_gettags:
    path: /webkul/gallery/tag
    defaults: { _controller: webkul.image_gallery_configuration.controller:getTagAction }
    methods: [GET]

image_gallery_version: 
    path: /webkul/gallery/version
    defaults: { _controller: webkul.image_gallery_configuration.controller:getModeVersionAction }
    methods: [GET]

webkulgallery_getgroups:
    path: /webkul/gallery/gallery-groups
    defaults: { _controller: webkul.image_gallery_configuration.controller:getGroupsAction }
    methods: [GET]

webkulgallery_tag_create:
    path: /webkul/gallery/tag/create
    defaults: { _controller: webkul.image_gallery_configuration.controller:addTagAction }
    methods: [POST]

# webkul_gallery_rest_index:
#     path: /webkul/gallery/list/rest
#     defaults: { _controller: webkul.image_gallery_configuration.controller:getGallerysAction }
#     methods: [GET]

# webkul_gallery_list_rest_index:
#     path: /webkul/gallery/list/rest
#     defaults: { _controller: webkul.image_gallery_configuration.controller:getGallerysdemoAction }
#     methods: [GET]

webkulgallery_asset_rest_index:
    path: /webkul/gallery/asset
    defaults: { _controller: webkul.image_gallery_configuration.controller:getGalleryAssetsAction }
    methods: [GET]

webkul_gallery_media_rest_get:
    path: /webkul/gallery/media/rest/data
    defaults: { _controller: webkul.image_gallery_configuration.controller:getMediaDetailAction }
    methods: [GET]

webkul_gallery_media_rest_get_image:
    path: /webkul/gallery/media/rest/image/data
    defaults: { _controller: webkul.image_gallery_configuration.controller:getImageForSlider }
    methods: [GET]

webkul_gallery_asset_edit:
    path: /webkul/gallery/{code}/edit
    requirements:
        code: '[a-zA-Z0-9_]+'

webkul_gallery_media_edit:
    path: /webkul/gallery/media/{code}/edit
    requirements:
        code: '[a-zA-Z0-9_]+'

webkul_gallery_asset_delete:
    path: /webkul/gallery/{code}/delete
    defaults: { _controller: webkul.image_gallery_configuration.controller:deleteAction }
    requirements:
        id: \d+
    methods: [DELETE]

webkul_gallery_media_rest_post:
    path: /webkul/gallery/media/saveimage
    defaults: { _controller: webkul_image.gallery.controller.rest.media:postAction }
    methods: [POST]

webkul_gallery_categorytree:
    path: /webkul/gallery/category/rest
    defaults: { _controller: webkul.image_gallery_configuration.controller:getCategoryAction }
    methods: [GET]

webkulgallery_categorytree_listtree:
    path: /webkul/gallery/category/list
    defaults: { _controller: webkul.image_gallery_configuration.controller:getCategoryAction }
    methods: [GET]    

webkulgallery_categorytree_children:
    path: /webkul/gallery/category/children
    defaults: { _controller: webkul.image_gallery_configuration.controller:getCategoryAction }

webkulgallery_media_download:
    path: /webkul/gallery/media/{identifier}/download
    defaults: { _controller: webkul_image.gallery.controller.media:downloadAction }
    methods: [GET]

webkulgallery_group_data_grid:
    path: /webkul/gallery/rest/custom-group-mapping/

webkul_gallery_group_delete:
    path: /webkul/gallery/{id}/deletegroup
    defaults: { _controller: webkul.image_gallery_configuration.controller:deleteGroupAction }

webkul_edit_media:
    path: /webkul/gallery/rest/media/url
    defaults: { _controller: webkul_image.gallery.controller.media:editMediaAction }

webkul_media_post:
    path: /webkul/gallery/media/save
    defaults: { _controller: webkul_image.gallery.controller.media:saveMediaAction }

        
webkul_media_editor:
    path: /webkul/gallery/media/editor
    defaults: { _controller: webkul_image.gallery.controller.media:editorMediaAction }
    methods: [GET]

# webkul_akeneo_translator_get:
#     path: /webkul/akeneo-translator/get
#     defaults: { _controller: webkul.translator_configuration.controller:getAction }
#     methods: [GET]

# webkul_transtor_locale_map_index:
#     path: /webkul/akeneo-translator/get-map-locale
#     defaults: { _controller: webkul.translator_configuration.controller:getLocaleMapListAction }
#     methods: [GET]

# webkul_translator_activated_locales_index:
#     path: /webkul/akeneo-translator/activatedlocales
#     defaults: { _controller: webkul.translator_configuration.controller:getLocaleListAction }
#     methods: [GET]

# webkul_akeneo_translator_configuration_post:
#     path: /webkul/akeneo-translator/rest/{tab}
#     defaults: { _controller: webkul.translator_configuration.controller:postAction, tab: credential }
#     methods: [POST]

# webkul_translator_activated_scope_index:
#     path: /webkul/akeneo-translator/activatedscope
#     defaults: { _controller: webkul.translator_configuration.controller:getScopeListAction }
#     methods: [GET]
