services:
    webkul.image.gallery.connector.service:
        class: 'Webkul\ImageGalleryBundle\Services\ImageGalleryConnector'
        public: true
        arguments:
            - '@service_container'
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.repository.category'
            - '@pim_catalog.repository.attribute'
            - '@pim_catalog.repository.attribute_option'
            - '@pim_catalog.repository.attribute_group'
            - '@pim_catalog.repository.currency'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.family'
            - '@pim_catalog.repository.family_variant'
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product_model'
            - '@pim_enrich.repository.job_instance'
            - '@router'
            - '@liip_imagine.controller'
            - '@pim_api.updater.product_model'
            - '@pim_catalog.saver.product_model'
            - '@pim_catalog.validator.product'

    webkul.image.gallery.temp_path.provider:
        class: Webkul\ImageGalleryBundle\Component\TempStoragePathProvider
        arguments:
            - '@service_container'

    webkul_gallery.content.security.policy:
        class: Webkul\ImageGalleryBundle\Twig\ContentSecurityPolicy
        arguments:
            - '@wkgallery_security.script_nonce_generator'
        tags:
            - { name: twig.extension }

    wkgallery_security.script_nonce_generator:
        class: Webkul\ImageGalleryBundle\Listener\ScriptNonceGenerator
        arguments:
            - '@request_stack'
            - '%kernel.secret%'

    quick_export_connector:
        class: Webkul\ImageGalleryBundle\ImageGalleryBundle
        tags:
            - { name: wk_quick_export_register }
