parameters:
    webkulgallery.updater.setter.media.class: Webkul\ImageGalleryBundle\Updater\Setter\MediaGroupSetter
    webkul_gallery_media.updater.media.class:   Webkul\ImageGalleryBundle\Updater\MediaUpdater

services:
    webkulgallery.updater.setter.media_group:
        public: false
        class: '%webkulgallery.updater.setter.media.class%'
        parent: pim_catalog.updater.setter.abstract
        arguments:
            - ['pim_catalog_gallery_group']
        tags:
            - { name: 'pim_catalog.updater.setter' }

    # webkulgallery.updater.copier.media_group:
    #     public: false
    #     class: '%pim_catalog.updater.copier.value.class%'
    #     parent: pim_catalog.updater.copier.abstract
    #     arguments:
    #         - '@pim_serializer'
    #         - ['pim_catalog_gallery_group']
    #         - ['pim_catalog_gallery_group']
    #     tags:
    #         - { name: 'pim_catalog.updater.copier' }

    webkul_gallery.updater.media:
        class: '%webkul_gallery_media.updater.media.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@webkul_gallery.repository.media'
            - '@validator'
            - '@akeneo_file_storage.file_storage.path_generator'
            - '@webkul.image.gallery.temp_path.provider'
            - '@akeneo_file_storage.file_storage.file.file_storer'
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            
