parameters:

services:    
    webkulgallery.writer.api.csv_gallery:
        class: 'Webkul\ImageGalleryBundle\Connector\Writer\GalleryWriter'
        arguments:
            - '@pim_connector.array_converter.standard_to_flat.product_model_localized'
            - '@pim_connector.factory.flat_item_buffer'
            - '@pim_connector.writer.file.product_model.flat_item_buffer_flusher'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.writer.file.media_exporter_path_generator'
            - ['pim_catalog_file', 'pim_catalog_image'] 
            - '@webkul.image.gallery.connector.service'
            - '@akeneo_file_storage.file_storage.filesystem_provider'
            - '@akeneo_file_storage.file_storage.file.output_file_fetcher'
   
    webkulgallery.writer.database.gallery:
        class: '%pim_connector.writer.database.class%'
        arguments:
            - '@webkul_gallery.saver.media'
            - '@akeneo_storage_utils.doctrine.object_detacher'