extensions:
    webkul-gallery-media-edit-form:
        module: webkul/gallery/edit/form
    
    webkul-gallery-media-edit-form-main-image:
        module: pim/form/common/main-image
        parent: webkul-gallery-media-edit-form
        targetZone: main-image
        config:
            path: bundles/imagegallery/images/akeneo_media_gallery.png

    # webkugallery-column:
    #     module: pim/menu/column
    #     parent: pim-menu
    #     position: 500
    #     targetZone: column
    #     config:
    #         stateCode: webkul-gallery-media-media-edit-form
    #         tab: pim-menu-webkul-gallery-media
    #         navigationTitle: pim_menu.navigation.asset

    # webkulgallery-navigation-block:
    #     module: pim/menu/navigation-block
    #     parent: webkugallery-column
    #     targetZone: navigation
    #     config:
    #         title: pim_menu.navigation.asset

    # webkulgallery-description-edit:
    #     module: webkul/gallery/menu/item
    #     parent: webkulgallery-navigation-block
    #     aclResourceId: image_gallery_configuration
    #     position: 100
    #     config:
    #         title: pim_menu.item.description
    #         to: webkul_gallery_asset_edit
    #         getCodeFromRoute: true
    
    # webkul-gallery-media-edit-form-breadcrumbs:
    #     module: pim/common/breadcrumbs
    #     parent: webkul-gallery-media-edit-form
    #     targetZone: breadcrumbs
    #     config:
    #         tab: pim-menu-webkul-gallery-media
    #         item: webkulgallery-description-edit

    webkul-gallery-media-edit-form-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-gallery-media-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    # webkul-gallery-media-edit-form-cache-invalidator:
    #     module: pim/cache-invalidator
    #     parent: webkul-gallery-media-edit-form
    #     position: 1000

    webkul-gallery-media-edit-form-label:
        module: pim/form/common/label
        parent: webkul-gallery-media-edit-form
        targetZone: title
        position: 90

    webkul-gallery-media-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: webkul-gallery-media-edit-form
        targetZone: buttons
        position: 50

    webkul-gallery-media-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: webkul-gallery-media-edit-form
        targetZone: buttons
        position: 110

    webkul-gallery-media-edit-form-save:
        module: pim/form/common/save-form
        parent: webkul-gallery-media-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: webkulgallery.asset.info.update_successful
            updateFailureMessage: webkulgallery.asset.info.update_failed
            notReadyMessage: webkulgallery.asset.info.field_not_ready
            url: webkul_gallery_asset_media_create_rest
            redirectAfter: webkul_gallery_asset_edit
            identifierParamName: code
            redirectAfterRouteIdentifierParamName: code
            excludedProperties: [attribute]

    webkul-gallery-media-edit-form-state:
        module: pim/form/common/state
        parent: webkul-gallery-media-edit-form
        targetZone: state
        position: 900
        config:
            entity: webkul-gallery-media-edit-form-properties-title

    webkul-gallery-media-edit-form-properties:
        module: pim/common/simple-view
        parent: webkul-gallery-media-edit-form
        # targetZone: self
        targetZone: content
        config:
            template: pim/template/form/tab/sections

    #properties tab
    webkul-gallery-media-edit-form-properties-common:
        module: pim/common/simple-view
        parent: webkul-gallery-media-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: webkulgallery.form.properties.section.common
                dropZone: content

    webkul-gallery-media-edit-form-properties-common-thumbnail:
        module: pim/form/common/fields/boolean
        parent: webkul-gallery-media-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: thumbnail
            label: webkulgallery.form.properties.label.thumbnail

    # webkul-gallery-media-edit-form-properties-title:
    #     module: pim/form/common/fields/text
    #     parent: webkul-gallery-media-edit-form-properties-common
    #     targetZone: content
    #     position: 100
    #     config:
    #         fieldName: title
    #         label: webkulgallery.form.properties.label.title
    
    webkul-gallery-media-edit-form-properties-description:
        module: pim/form/common/fields/textarea
        parent: webkul-gallery-media-edit-form-properties-common
        targetZone: content
        position: 120
        config:
            fieldName: description
            label: webkulgallery.form.properties.label.description
    
    # # media tab
    webkul-gallery-media-edit-form-properties-media:
        module: pim/common/simple-view
        parent: webkul-gallery-media-edit-form-properties
        targetZone: accordion
        position: 90
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: webkulgallery.form.properties.section.media
                dropZone: content

    webkul-gallery-media-edit-form-properties-common-media:
        # module: pim/form/common/fields/text
        module: webkul/gallery/image-media-field
        parent: webkul-gallery-media-edit-form-properties-media
        targetZone: content
        position: 100
        config:
            fieldName: media
            label: webkulgallery.form.properties.label.media
