# override array converter standard to flat
parameters:
  pim_connector.array_converter.standard_to_flat.product.class: Webkul\Magento2BundleProductBundle\Component\Connector\ArrayConverter\StandardToFlat\Product
  pim_conector.array_coverter.flat_to_standard.product.class: Webkul\Magento2BundleProductBundle\Component\Connector\ArrayConverter\FlatToStandard\Product

services:
  pim_connector.array_converter.standard_to_flat.product:
      class: '%pim_connector.array_converter.standard_to_flat.product.class%'
      arguments:
            - '@pim_connector.array_converter.standard_to_flat.product.product_value_converter'
  
  pim_connector.array_converter.flat_to_standard.product:
        class: '%pim_conector.array_coverter.flat_to_standard.product.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.association_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - '@pim_connector.array_converter.flat_to_standard.product.field_converter'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_merger'
            - '@pim_connector.array_converter.flat_to_standard.product.columns_mapper'
            - '@pim_connector.array_convertor.checker.fields_requirement'
            - '@pim_catalog.repository.attribute'
            - '@pim_connector.array_converter.flat_to_standard.product_value'