services:    
    pim_datagrid.datasource.adapter_resolver:
        class: '%pim_datagrid.datasource.adapter_resolver.class%'
        arguments:
            - '%pim_filter.datasource.orm_adapter.class%'
            - '%pim_filter.datasource.product_orm_adapter.class%'
        calls:
            - [addProductDatasource, ['pim_datasource_product']]
            - [addProductDatasource, ['pim_datasource_associated_product']]
            - [addProductDatasource, ['pim_datasource_associated_product_model']]
            - [addProductDatasource, ['pim_datasource_group_product']]
            - [addProductDatasource, ['wk_magento2_datasource_product']]
            