services:
    # form entry 
    webkul_magento2.group_product.provider.form.job_instance:
        class: '%pim_enrich.provider.form.job_instance.class%'
        arguments:
            -
                '%webkul_magento2_group_product_import.job%': pim-job-instance-magento2-product-import
        tags:
            - { name: pim_enrich.provider.form }
