Webkul\Magento2Bundle\Entity\CredentialConfig:
    type: entity
    table: wk_magento2_credentials_mapping
    repositoryClass: Webkul\Magento2Bundle\Repository\CredentialConfigRepository
    indexes:
        wk_magento2_credentials_mapping:
            columns: [ hostName, authToken, defaultSet, active]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        hostName:
            type: string
            length: 255
            unique: true
        authToken:
            type: string
            length: 255
        resources:
            type: text
            nullable: true
        defaultSet:
            type: boolean
            options:
                default: 0
        active:
            type: boolean
            options:
                default: 0