Webkul\Magento2Bundle\Entity\EntityTracker:
    type: entity
    table: wk_magento2_entity_tracker
    indexes:
        wk_magento2_entity_tracker:
            columns: [ entityType, code, action]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        entityType:
            type: string
            length: 255
        code:
            type: string
            length: 255
        action:
            type: string
            length: 255
        lastUpdatedAt:
            type: datetime
    lifecycleCallbacks:
        prePersist: [ setLastUpdatedAtValue ]