Webkul\Magento2Bundle\Entity\ProductMapping:
    type: entity
    table: wk_magento2_product_mapping
    repositoryClass: Webkul\Magento2Bundle\Repository\ProductMappingRepository
    indexes:
        wk_magento2_product_mapping:
            columns: [ sku, type]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        sku:
            type: string
            length: 255
        type: 
            type: string
            length: 255