parameters:
  webkul_magento_csv.processor.normalization.product.class: Webkul\Magento2Bundle\Connector\Processor\Csv\Akeneo2_2\ProductProcessor

services:
    webkul_magento2.processor.magento_normalization.product:
        class: 'Webkul\Magento2Bundle\Connector\Processor\ProductProcessor'
        arguments:
            - '@webkul_magento2.product.normalizer'
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.attribute'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_connector.processor.bulk_media_fetcher'
            - '@pim_catalog.values_filler.product'
            - '@router'
            - '@magento2.connector.service'
            
    webkul_magento_csv.processor.normalization.product:
        class: '%webkul_magento_csv.processor.normalization.product.class%'
        parent: pim_connector.processor.normalization.product
        # arguments:
        #     - '@pim_catalog.normalizer.standard.product'
        #     - '@pim_catalog.repository.channel'
        #     - '@pim_catalog.repository.attribute'
        #     - '@pim_connector.processor.bulk_media_fetcher'
        #     - '@?pim_catalog.values_filler.product'
        #     - '@pim_connector.doctrine.cache_clearer'

    # associations
    webkul_magento2.processor.magento_normalization.product.association:
        class: 'Webkul\Magento2Bundle\Connector\Processor\ProductAssociationProcessor'
        arguments:
            - '@webkul_magento2.product.normalizer'
            - '@akeneo_storage_utils.doctrine.object_detacher'
            - '@pim_catalog.repository.channel'
            - '@?pim_catalog.values_filler.product'

    webkul_magento2.processor.magento_normalization.product_model.association:
        class: 'Webkul\Magento2Bundle\Connector\Processor\ProductModelAssociationProcessor'
        parent: pim_connector.processor.normalization.product_model
        # arguments:
        #     - '@pim_catalog.normalizer.standard.product_model'
        #     - '@pim_catalog.repository.channel'
        #     - '@pim_catalog.repository.attribute'
        #     - '@pim_connector.processor.bulk_media_fetcher'
        #     - '@?pim_catalog.values_filler.entity_with_family_variant'
        #     - '@pim_connector.doctrine.cache_clearer'

        #         - '@pim_catalog.product_model.fill_missing_values'

    #rabbitMQ
    # only for magento EE
    # webkul_magento2.processor.buffered.product_models:
    #     class: Webkul\Magento2Bundle\Connector\Processor\BufferedProductModelProcessor
    #     arguments:
    #         - '@pim_catalog.normalizer.standard.product'
    #         - '@pim_catalog.repository.channel'
    #         - '@pim_catalog.repository.attribute'
    #         - '@pim_connector.processor.bulk_media_fetcher'
    #         - '@?pim_catalog.values_filler.product'
    #         - '@pim_connector.doctrine.cache_clearer'
