datagrid:
    product-grid:
        mass_actions:
            quick_export_magento2:
                type: export
                label: pim.grid.mass_action.quick_export.magento2
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:                   
                    _format: html
                    _contentType: text/html
                    _jobCode: magento2_product_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export
            quick_export_grid_context_magento2:
                type: export
                label: pim.grid.mass_action.quick_export.magento2
                handler: product_quick_export
                route: pim_datagrid_export_product_index
                route_parameters:                   
                    _format: html
                    _contentType: text/html
                    _jobCode: magento2_product_quick_export
                    _displayedColumnsOnly: 0
                context:
                    withHeader: true
                messages:
                    empty_selection: pim_datagrid.mass_action.delete.empty_selection
                launcherOptions:
                    group: quick_export