datagrid:
    webkul-magento2-credentials-mapping-grid:
        extended_entity_name: Webkul\Magento2Bundle\Entity\CredentialConfig
        options:
            entityHint: CredentialConfig
            manageFilters: false
        source:
            acl_resource: webkul_magento2_connector_configuration
            type: magento2_datasource_credentials
            entity: 'Webkul\Magento2Bundle\Entity\CredentialConfig'
            query:
                select:
                    - wem.id
                    - wem.hostName
                    - wem.active
                    - wem.defaultSet
                from:
                    - { table: 'Webkul\Magento2Bundle\Entity\CredentialConfig', alias: wem }
        columns:
            hostName:
                label: magento2.form.properties.host_name.title
                frontend_type: label
            active:
                label: Activated
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
            defaultSet:
                label: Default for QuickExport
                type: twig
                template: PimDataGridBundle:Property:activated.html.twig
                frontend_type: html
        sorters:
            columns:
                hostName:
                    data_name: wem.hostName
                active:
                    data_name: wem.active
            default:
                url: '%oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC'

        filters:
            columns:
                hostName:
                    type: search
                    data_name: wem.hostName
                active:
                    type:      boolean
                    label:     Activated
                    data_name: wem.active
        properties:
            id: ~
            edit_link:
                type: url
                route: webkul_magento2_credentials_edit
                params:
                    - id
            toggle_link:
                type: url
                route: webkul_magento2_credentials_change_status
                params:
                    - id
            delete_link:
                type: url
                route: webkul_magento2_credentials_delete
                params:
                    - id
            quick_export_default_link:
                type: url
                route: webkul_magento2_credentials_change_default_quickexport
                params:
                    - id

        actions:
            toggle:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--switch
                type:       toggle-product
                label:        Change Activate status
                link:         toggle_link
                acl_resource: webkul_magento2_connector_configuration
            delete:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--trash
                type:          delete
                label:         Delete
                link:          delete_link
                acl_resource:  webkul_magento2_connector_configuration
            edit:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--edit
                type:      navigate
                label:     Edit
                link:      edit_link
                acl_resource: webkul_magento2_connector_configuration
                rowAction: true
            defaultSet:
                launcherOptions:
                    className: AknIconButton AknIconButton--small AknIconButton--switch
                type: toggle-product
                label:        Set Default for Quick Export
                link:         quick_export_default_link
                acl_resource: webkul_magento2_connector_configuration