Akeneo\Pim\Structure\Component\Model\Attribute:
    constraints:
        - Akeneo\Pim\Structure\Component\Validator\Constraints\NullProperties:
            message: This attribute cannot have options.
            properties:
                - auto_option_visual_swatch
            groups:
                - pim_catalog_identifier
                - pim_catalog_text
                - pim_catalog_textarea
                - pim_catalog_number
                - pim_catalog_price_collection
                - pim_catalog_file
                - pim_catalog_image
                - pim_catalog_boolean
                - pim_catalog_date
                - pim_catalog_metric
                - pim_reference_data_multiselect
                - pim_reference_data_simpleselect