extensions:
    webkul-gallery-create-form:
        module: pim/form/common/edit-form

    webkul-gallery-create-form-main-image:
        module: pim/form/common/main-image
        parent: webkul-gallery-create-form
        targetZone: main-image
        config:
            path: bundles/imagegallery/images/akeneo_media_gallery.png

    webkul-gallery-create-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: webkul-gallery-create-form
        position: 1000

    webkul-gallery-create-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: webkul-gallery-create-form
        targetZone: content
        position: 90

    webkul-gallery-create-form-label:
        module: pim/form/common/label
        parent: webkul-gallery-create-form
        targetZone: title
        position: 110

    webkul-gallery-create-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: webkul-gallery-create-form
        targetZone: buttons
        position: 110

    webkul-gallery-create-form-save:
        module: pim/form/common/save-form
        parent: webkul-gallery-create-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: pim_enrich.entity.attribute_group.info.update_successful
            updateFailureMessage: pim_enrich.entity.attribute_group.info.update_failed
            notReadyMessage: pim_enrich.entity.attribute_group.info.field_not_ready
            url: webkul_gallery_media_create_rest
            method: PUT
            redirectAfter: webkul_gallery_configuration

    webkul-gallery-create-form-state:
        module: pim/form/common/state
        parent: webkul-gallery-create-form
        targetZone: state
        position: 900
        config:
            entity: webkul_gallery.asset.title

    webkul-gallery-create-form-properties-tab:
        module: pim/common/tab
        parent: webkul-gallery-create-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_enrich.form.asset.tab.properties.title

    webkul-gallery-create-form-properties:
        module: pim/common/simple-view
        parent: webkul-gallery-create-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    webkul-gallery-create-form-properties-general:
        module: pim/create/properties/general
        parent: webkul-gallery-create-form-properties
        targetZone: accordion
        position: 100
        config:
            sectionTitle: pim_enrich.form.channel.tab.properties.general
            codeLabel: pim_enrich.form.channel.tab.properties.code
