extensions:
    webkul-gallery-create-groupmodal:
        module: pim/form/common/creation/modal
        config:
            labels:
                title: pim_enrich.entity.group.create_popin.title
                subTitle: webkul_gallery.item.group
            picture: illustrations/Family.svg
            successMessage: webkul_gallery.entity.asset.message.created
            editRoute: webkul_akeneo_gallery_index
            postUrl: webkul_gallery_group_create_rest
            routerKey: code

    webkul-gallery-create-groupcode:
        module: webkulgallery/form/common/creation/groupfield
        parent:  webkul-gallery-create-groupmodal
        targetZone: fields
        position: 10        
        config:
            identifier: code
            label: pim_enrich.entity.create_popin.code
