extensions:
    webkul-gallery-edit-form:
        module: webkul/gallery/edit/form
    
    webkul-gallery-edit-form-main-image:
        module: pim/form/common/main-image
        parent: webkul-gallery-edit-form
        targetZone: main-image
        config:
            path: bundles/imagegallery/images/akeneo_media_gallery.png

    # webkugallery-column:
    #     module: pim/menu/column
    #     parent: pim-menu
    #     position: 500
    #     targetZone: column
    #     config:
    #         stateCode: webkul-gallery-edit-form
    #         tab: webkul-gallery-edit-form
    #         navigationTitle: pim_menu.navigation.asset

    # webkulgallery-navigation-block:
    #     module: pim/menu/navigation-block
    #     parent: webkugallery-column
    #     targetZone: navigation
    #     config:
    #         title: pim_menu.navigation.asset

    webkulgallery-description-edit:
        module: webkul/gallery/menu/item
        parent: webkulgallery-navigation-block
        aclResourceId: image_gallery_configuration
        position: 100
        config:
            title: pim_menu.item.description
            to: webkul_gallery_asset_edit
            getCodeFromRoute: true
    
    webkul-gallery-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: webkul-gallery-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-webkul-gallery
            item: webkulgallery-description-edit

    webkul-gallery-edit-form-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-gallery-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout

    # webkul-gallery-edit-form-cache-invalidator:
    #     module: pim/cache-invalidator
    #     parent: webkul-gallery-edit-form
    #     position: 1000

    webkul-gallery-edit-form-label:
        module: pim/form/common/label
        parent: webkul-gallery-edit-form
        targetZone: title
        position: 90

    webkul-gallery-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: webkul-gallery-edit-form
        targetZone: buttons
        position: 50

    webkul-gallery-edit-form-delete:
        module: webkulgallery/asset-edit-form/delete
        parent: webkul-gallery-edit-form-secondary-actions
        position: 100
        targetZone: secondary-actions
        aclResourceId: image_gallery_configuration
        config:
            trans:
                title: confirmation.remove.galleryasset
                subTitle: webkul_gallery.item.asset
                content: pim_enrich.confirmation.delete_item
                success: flash.asset.removed
                failed: error.removing.asset
            redirect: webkul_akeneo_gallery_index

    webkul-gallery-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: webkul-gallery-edit-form
        targetZone: buttons
        position: 110

    webkul-gallery-edit-form-save:
        module: pim/form/common/save-form
        parent: webkul-gallery-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: webkulgallery.asset.info.update_successful
            updateFailureMessage: webkulgallery.asset.info.update_failed
            notReadyMessage: webkulgallery.asset.info.field_not_ready
            url: webkul_gallery_asset_create_rest
            # redirectAfter: webkul_akeneo_gallery_index
            identifierParamName: code
            excludedProperties: [attribute]

    webkul-gallery-edit-form-state:
        module: pim/form/common/state
        parent: webkul-gallery-edit-form
        targetZone: state
        position: 900
        config:
            entity: webkul-gallery-edit-form-properties-title

    webkul-gallery-edit-form-properties:
        module: pim/common/simple-view
        parent: webkul-gallery-edit-form
        # targetZone: self
        targetZone: content
        config:
            template: pim/template/form/tab/sections

    #properties tab
    webkul-gallery-edit-form-properties-common:
        module: pim/common/simple-view
        parent: webkul-gallery-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: webkulgallery.form.properties.section.common
                dropZone: content

    webkul-gallery-edit-form-properties-common-code:
        module: pim/form/common/fields/text
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: code
            label: webkulgallery.form.properties.label.code
            required: true
            readOnly: true

    webkul-gallery-edit-form-properties-common-starred:
        module: pim/form/common/fields/boolean
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: starred
            label: webkulgallery.form.properties.label.starred

    webkul-gallery-edit-form-properties-title:
        module: pim/form/common/fields/text
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 100
        config:
            fieldName: title
            label: webkulgallery.form.properties.label.title

    webkul-gallery-edit-form-properties-alt:
        module: pim/form/common/fields/text
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 110
        config:
            fieldName: alt
            label: webkulgallery.form.properties.label.alt
        
    webkul-gallery-edit-form-properties-description:
        module: pim/form/common/fields/textarea
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 120
        config:
            fieldName: description
            label: webkulgallery.form.properties.label.description    

    webkul-gallery-edit-form-properties-expiration-date:
        module: webkulgallery/form/date
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 130
        config:
            fieldName: expiration_date
            label: webkulgallery.form.properties.label.expiration_date

    webkul-gallery-edit-form-properties-tag:
        module: webkulgallery/form/gallery-tags
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 140
        config:
            fieldName: tag
            label: webkulgallery.form.properties.label.tag

    webkul-gallery-edit-form-properties-group:
        module: webkulgallery/form/gallery-group
        parent: webkul-gallery-edit-form-properties-common
        targetZone: content
        position: 150
        config:
            fieldName: group
            label: webkulgallery.form.properties.label.group

    # # media tab
    webkul-gallery-edit-form-properties-media:
        module: pim/common/simple-view
        parent: webkul-gallery-edit-form-properties
        targetZone: accordion
        position: 90
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: webkulgallery.form.properties.section.media
                dropZone: content

    webkul-gallery-edit-form-properties-common-media:
        # module: pim/form/common/fields/text
        module: webkul/gallery/media-field
        parent: webkul-gallery-edit-form-properties-media
        targetZone: content
        position: 100
        config:
            fieldName: medias
            label: webkulgallery.form.properties.label.media
