parameters:
    webkul_gallery.factory.asset_value.class: Webkul\ImageGalleryBundle\Factory\Akeneo4\GalleryMediaValueFactory

services:
    webkul_asset_attribute.factory.asset_attribute_value:
        class: '%webkul_gallery.factory.asset_value.class%'
        public: false
        arguments:
            - '%webkulgallery.entity.value.class%'
            - 'pim_catalog_gallery_group'
        tags:
            - { name: 'akeneo.pim.enrichment.factory.product_value' }

    webkul_gallery.pim.enrichment.completeness.mask_item_generator.media_assets:
        public: false
        class: 'Webkul\ImageGalleryBundle\Completeness\DefaultMaskItemGenerator'
        tags: [{ name: akeneo.pim.enrichment.completeness.mask_item_generator }]

