parameters:

services:
    # steps
    webkul.step.amasty_product_attachments_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'amasty_product_attachments_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@webkul_magento_csv.processor.normalization.product'
            - '@magento2.writer.api.amasty_product_attachments'
            - 10

    webkul.step.quick_amasty_product_attachments_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'amasty_quick_product_attachments_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_enrich.reader.database.product_and_product_model'
            - '@pim_enrich.connector.processor.quick_export.product'
            - '@magento2.writer.api.amasty_product_attachments'
            - 10

    webkul.step.amasty_product_model_attachments_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'amasty_product_model_attachments_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product_model'
            - '@pim_connector.processor.normalization.product_model'
            - '@magento2.writer.api.amasty_product_attachments'
            - 10

    #writers
    magento2.writer.api.amasty_product_attachments:
        class: 'Webkul\Magento2Bundle\Connector\Writer\AmastyProductAttachmentWriter'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2.connector.service'