services:
    Webkul\Magento2Bundle\Command\Magento2LessFileUpdateCommand:
        tags:
            - { name: console.command }
            
    Webkul\Magento2Bundle\Command\Magento2ModuleInstallationCommand:
        tags:
            - { name: console.command }
            
    Webkul\Magento2Bundle\Command\CorrectShardTimeoutCommand:
        tags:
            - { name: console.command }

    Webkul\Magento2Bundle\Command\DataMappingCommand:
        tags:
            - { name: console.command }

    Webkul\Magento2Bundle\Command\RemoveUnusedFilesCommand:
        tags:
            - { name: console.command }

    Webkul\Magento2Bundle\Command\UpdateHostCommand:
        tags:
            - { name: console.command }
