extensions:
    # menu item
    pim-menu-magento2:
        module: pim/menu/tab
        parent: pim-menu
        position: 100
        targetZone: mainMenu
        aclResourceId: webkul_magento2_connector_configuration
        config:
            title: Magento2 Connector
            iconModifier: iconWebkulMagento2
            to: webkul_magento2_connector_configuration

    # magento2_configuration_form:
    webkul-magento2-connector-configuration-form:
        module: magento2/form/configuration

    webkul-magento2-connector-configuration-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: webkul-magento2-connector-configuration-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-magento2

    webkul-magento2-connector-configuration-title:
        module: pim/common/grid-title
        parent: webkul-magento2-connector-configuration-form
        targetZone: title
        config:
            title: magento2.connector.title
            countable: false

    webkul-magento2-connector-configuration-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-magento2-connector-configuration-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout    

    # Save Button
    webkul-magento2-connector-configuration-save:
        module: magento2/form/configuration/save
        parent: webkul-magento2-connector-configuration-form
        targetZone: buttons
        position: 100

    webkul-magento2-connector-configuration-tab-importjobs:
        module: magento2/form/configuration/importjobs
        parent: webkul-magento2-connector-configuration-form
        targetZone: buttons
        position: 110

    webkul-magento2-connector-configuration-tab-jobs:
        module: magento2/form/configuration/jobs
        parent: webkul-magento2-connector-configuration-form
        targetZone: buttons
        position: 120

    # Tabs
    webkul-magento2-connector-configuration-tabs:
        module: pim/form/common/form-tabs
        parent: webkul-magento2-connector-configuration-form
        targetZone: content
        position: 100

    webkul-magento2-connector-configuration-tab-documentation:
        module: magento2/form/configuration/tab/documentation
        parent: webkul-magento2-connector-configuration-tabs
        targetZone: container
        position: 110
        config:
            title: magento2.documentation

    webkul-magento2-connector-configuration-tab-credential:
        module: magento2/form/configuration/tab/credential
        parent: webkul-magento2-connector-configuration-tabs
        targetZone: container
        position: 120
        config:
            title: magento2.credentials

    #datagrid form multi-credentials 
    webkul-magento2-connector-credentials-index:
        module: pim/common/simple-view
        parent: webkul-magento2-connector-configuration-tab-credential
        config:
            template: magento2/template/job/default-template
        forwarded-events:
            grid_load:start: grid_load:start
            grid_load:complete: grid_load:complete

    webkul-magento2-connector-credentials-index-grid-container:
        module: pim/common/simple-view
        parent: webkul-magento2-connector-credentials-index
        targetZone: content
        config:
            template: pim/template/form/index/index

    webkul-magento2-connector-credentials-index-filters-list:
        module: oro/datafilter/filters-list
        parent: webkul-magento2-connector-credentials-index-grid-container
        targetZone: filters

    webkul-magento2-connector-credentials-index-filters-manage:
        module: oro/datafilter/filters-button
        parent: webkul-magento2-connector-credentials-index-grid-container
        targetZone: filters

    webkul-magento2-connector-credentials-index-pagination:
        module: oro/datagrid/pagination-input
        parent: webkul-magento2-connector-credentials-index-grid-container
        targetZone: toolbar
        config:
            gridName: webkul-magento2-credentials-mapping-grid

    webkul-magento2-connector-credentials-index-grid:
        module: pim/form/common/index/grid
        parent: webkul-magento2-connector-credentials-index-grid-container
        position: 1000
        config:
            alias: webkul-magento2-credentials-mapping-grid

    webkul-magento2-connector-credentials-index-create-button:
        module: pim/form/common/index/create-button
        parent: webkul-magento2-connector-credentials-index
        targetZone: buttons
        position: 100
        aclResourceId: webkul_magento2_connector_configuration
        config:
           iconName:  plus
           title:     webkul_magento2_connector.export_mapping.index.create_btn
           modalForm: webkul-magento2-connector-create-instance-modal

    # webkul-magento2-connector-credentials-index-mass-actions:
    #     module: pim/grid/mass-actions
    #     parent: webkul-magento2-connector-credentials-index
    #     targetZone: bottom-panel
    #     config:
    #         label: webkul_magento2_connector.entity.export_mapping.selected

    # webkul-magento2-connector-credentials-index-actions-panel:
    #     module: oro/datagrid/actions-panel
    #     parent: webkul-magento2-connector-credentials-index-mass-actions
    #     targetZone: actions-panel

    # end credentials

    # webkul-magento2-connector-configuration-tab-store-mapping:
    #     module: magento2/form/configuration/tab/storeMapping
    #     parent: webkul-magento2-connector-configuration-tabs
    #     targetZone: container
    #     position: 130
    #     config:
    #         title: magento2.store_mapping

    webkul-magento2-connector-configuration-tab-mapping:
        module: magento2/form/configuration/tab/mapping
        parent: webkul-magento2-connector-configuration-tabs
        targetZone: container
        position: 140
        config:
            title: magento2.attribute_mapping

    webkul-magento2-connector-configuration-tab-association:
        module: magento2/form/configuration/tab/association
        parent: webkul-magento2-connector-configuration-tabs
        targetZone: container
        position: 150
        config:
            title: magento2.attribute_association

    webkul-magento2-connector-configuration-tab-otherSettings:
        module: magento2/form/configuration/tab/otherSettings
        parent: webkul-magento2-connector-configuration-tabs
        targetZone: container
        position: 160
        config:
            title: magento2.attribute_otherSettings
    

    webkul-magento2-connector-configuration-state:
        module: pim/form/common/state
        parent: webkul-magento2-connector-configuration-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.title        