services:
    wk_magento2.entity_modification.listener:
        class: Webkul\Magento2Bundle\EventListener\EntityModificationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2.connector.service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.post_save, method: onPostSave }
    
    wk_magento2.entity_modification.listener-2:
        class: Webkul\Magento2Bundle\EventListener\EntityModificationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2.connector.service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.pre_save, method: onPreSave }

    wk_magento2.entity_deletion.listener:
        class: Webkul\Magento2Bundle\EventListener\EntityModificationListener
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2.connector.service'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.pre_remove, method: onPreRemove }

    wk_magento2_version_compatibility_kernal_request.listener:  
        class: 'Webkul\Magento2Bundle\EventListener\AkeneoVersionsCompatibility'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernalRequest }

    wk_magento2_version_compatibility_console_command.listener:  
        class:  'Webkul\Magento2Bundle\EventListener\AkeneoVersionsCompatibility'          
        tags:
            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand }
                