parameters:
    webkul_magento2_connector_data_mapping_mass_delete.class: Webkul\Magento2Bundle\Extension\MassAction\Handler\DeleteDataMappingsMassActionHandler
services:
    # webkul_magento2_connector_data_mapping_mass_delete:
    #     class: '%webkul_magento2_connector_data_mapping_mass_delete.class%'
    #     parent: pim_datagrid.extension.mass_action.handler.delete
    #     tags:
    #         - { name: pim_datagrid.extension.mass_action.handler, alias: webkul_magento2_connector_data_mapping_mass_delete }

    webkul_magento2_connector_data_mapping_mass_delete.wk_mapping_mass_delete:
        # class: '%webkul_magento2_connector_data_mapping_mass_delete.class%'
        class: '%pim_datagrid.extension.mass_action.type.delete.class%'
        shared: false
        tags:
            - { name: oro_datagrid.extension.mass_action.type, type: delete }