parameters:
    pim_catalog.normalizer.standard.product.price.class: Webkul\Magento2Bundle\Normalizer\PriceNormalizer

services:
    pim_catalog.normalizer.standard.product.price:  
        class: '%pim_catalog.normalizer.standard.product.price.class%'
        tags:
            - { name: pim_serializer.normalizer, priority: 90 }
            - { name: pim_standard_format_serializer.normalizer, priority: 90 }