parameters:
    magento2.properties.normalizer.class: Webkul\Magento2Bundle\Component\Normalizer\PropertiesNormalizer
    webkul_magento2.family.normalization.class: Webkul\Magento2Bundle\Connector\Processor\AttributeSetProcessor
    # magento2.assosiations.normalizer.class: Webkul\Magento2Bundle\Component\Normalizer\AssociationsNormalizer

services:
    # webkul_magento2.processor.magento_normalization.product:
    #     class: 'Webkul\Magento2Bundle\Connector\Processor\ProductProcessor'
    #     arguments:
    #         - '@webkul_magento2.product.normalizer'
    #         - '@pim_catalog.repository.channel'
    #         - '@pim_catalog.repository.attribute'
    #         - '@akeneo_storage_utils.doctrine.object_detacher'
    #         - '@pim_connector.processor.bulk_media_fetcher'
    #         - '@pim_catalog.values_filler.product'
    #         - '@router'
    #         - '@magento2.connector.service'

    webkul_magento2.product.normalizer:
        class: '%pim_catalog.normalizer.standard.product.class%'        
        arguments:
            - '@webkul_magento2.properties.normalizer'
            - '@pim_catalog.normalizer.standard.product.associations' # - '@webkul_magento2.assosiations.normalizer'
      
    webkul_magento2.properties.normalizer:
        class: '%magento2.properties.normalizer.class%'
        arguments:
            - '@pim_catalog.filter.chained'
            - '@magento2.connector.service'
        tags:
            - { name: pim_serializer.normalizer, priority: 40 }
            - { name: pim_standard_format_serializer.normalizer, priority: 40 }

    # webkul_magento2.processor.quick_export.product:
    #     class: 'Webkul\Magento2Bundle\Connector\Processor\ProductQuickProcessor'
    #     arguments:
    #         - '@pim_catalog.normalizer.standard.product'
    #         - '@pim_catalog.repository.channel'
    #         - '@pim_catalog.repository.attribute'
    #         - '@?pim_catalog.values_filler.product'
    #         - '@akeneo_storage_utils.doctrine.object_detacher'
    #         - '@pim_user.provider.user'
    #         - '@security.token_storage'
    #         - '@pim_connector.processor.bulk_media_fetcher'
    
    # metric attribute option processor
    webkul_magento2.product.metric_attribute_option.processor:
        class: 'Webkul\Magento2Bundle\Connector\Processor\MetricOptionProcessor'
    
    webkul_magento2.magento2.processor.normalization.product_model:
        class: 'Webkul\Magento2Bundle\Connector\Processor\Csv\ProductModelProcessor'
        parent: 'pim_connector.processor.normalization.product_model'

    webkul_magento2.magento2.processor.normalization.product:
        class: 'Webkul\Magento2Bundle\Connector\Processor\Csv\ProductProcessor'
        parent: 'pim_connector.processor.normalization.product'