parameters:

services:
    # steps
    webkul.step.product_attachments_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'product_attachments_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product'
            - '@webkul_magento_csv.processor.normalization.product'
            - '@magento2.writer.api.product_attachments'
            - 10

    webkul.step.product_model_attachments_export:
        class: '%pim_connector.step.item_step.class%'
        arguments:
            - 'product_model_attachments_export'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@pim_connector.reader.database.product_model'
            - '@pim_connector.processor.normalization.product_model'
            - '@magento2.writer.api.product_attachments'
            - 10

    #writers
    magento2.writer.api.product_attachments:
        class: 'Webkul\Magento2Bundle\Connector\Writer\ProductAttachmentWriter'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@magento2.connector.service'
