parameters:
    webkul.magento2.repository.data_mapping.class: Webkul\Magento2Bundle\Repository\DataMappingRepository
    magento2.entity.data_mapping.class:     Webkul\Magento2Bundle\Entity\DataMapping
    webkul_magento2.entity.category.searchable: Webkul\Magento2Bundle\Repository\CategorySearchableRepository
    webkul_magento2.entity.attribute.searchable: Webkul\Magento2Bundle\Repository\AttributeSearchableRepository

services:    
    webkul.magento2.repository.data_mapping:
        class: '%webkul.magento2.repository.data_mapping.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%magento2.entity.data_mapping.class%'

    webkul_magento2.repository.category.search:
        class: '%webkul_magento2.entity.category.searchable%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.category.class%'

    webkul_magento2.repository.attribute.search:
        class: '%webkul_magento2.entity.category.searchable%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%pim_catalog.entity.attribute.class%'
    