# magento2_tier_pricing:
#     resource: "@Magento2TierPricingBundle/Resources/config/routing.yml"
#     prefix:   / 
    
webkul_magento2_connector_configuration:
    path: /magento2-configuration

webkul_magento2_connector_configuration_get:
    path: /magento2-configuration/rest
    defaults: { _controller: wk_magento2_configuration_controller:getAction }
    methods: [GET]

webkul_magento2_connector_configuration_post:
    path: /magento2-configuration/rest/{tab}
    defaults: { _controller: wk_magento2_configuration_controller:postAction, tab: credential }
    methods: [POST]

webkul_magento_connector_configuration_action:
    path: /magento2-configuration/rest/fields
    defaults: { _controller: wk_magento2_configuration_controller:getDataAction }
    methods: [GET]
    
webkul_magento_connector_configuration_attributes_action:
    path: /magento2-configuration/rest/mapping-attributes
    defaults: { _controller: wk_magento2_configuration_controller:getMappingAttributesDataAction }
    methods: [GET]

webkul_magento2_connector_configuration_getstoreview:
    path: /magento2-configuration/storeview
    defaults: { _controller: wk_magento2_configuration_controller:postStoreViewsandCheckCredentialAction }
    methods: [POST]

webkul_magento2_connector_configuration_get_file:
    path: /media/csv-file
    defaults: { _controller: wk_magento2_configuration_controller:getCsvFileAction }
    methods: [GET]    

webkul_magento_connector_configuration_credential-readonly-parameters:
    path: /magento2-configuration/rest/credentail-readonly-parameters
    defaults: { _controller: wk_magento2_configuration_controller:getCredentailReadonlyParametersAction }
    methods: [GET]

#Job Instace class Get
akeneo-magento2-job-instance-class:
    path: /magento2-configuration/rest/job-instance-class/
    defaults: { _controller: wk_magento2_configuration_controller:getJobInstanceClassAction }
    methods: [GET]
 
webkul_magento2_credentials_create:
    path: /magento2-configuration/credential
    defaults: { _controller: Magento2Bundle:Rest\Credential:add }
    methods: [POST]

webkul_magento2_credentials_update:
    path: /magento2-configuration/credential/update
    defaults: { _controller: Magento2Bundle:Rest\Credential:add }
    methods: [POST]    

webkul_magento2_credentials_change_status:
    path: /magento2-configuration/credential/{id}/toggle-status
    defaults: { _controller: Magento2Bundle:Rest\Credential:toggleStatus }

webkul_magento2_credentials_delete:
    path: /magento2-configuration/credential/{id}/delete
    defaults: { _controller: Magento2Bundle:Rest\Credential:delete }

webkul_magento2_credentials_get:
    path: /magento2-configuration/rest/{id}
    defaults: { _controller: Magento2Bundle:Rest\Credential:get }    
    methods: [GET]

webkul_magento2_credentials_get_all:
    path: /magento2-configuration/credential/rest
    defaults: { _controller: Magento2Bundle:Rest\Credential:getAll }    
    methods: [GET]

webkul_magento2_credentials_edit:
    path: /magento2-configuration/rest/edit/{id}

webkul_magento2_credentials_change_default_quickexport:
    path: /magento2-configuration/credential/default
    defaults: { _controller: Magento2Bundle:Rest\Credential:changeDefault }
    methods: [GET,POST,PUT]

webkul_magento2_media_rest_post:
    path: /media/webkul/
    defaults: { _controller: webkul.magento2.controller.rest.media:postAction }
    methods: [POST]   

#Job Instace class Get
# akeneo-magento2-job-instance-class:
#     path: /magento2-configuration/rest/job-instance-class/
#     defaults: { _controller: Magento2Bundle:Rest\Configuration:getJobInstanceClass }
#     methods: [GET]

magento2_custom_category_rest_list:
    path: /rest/custom-category-rootcode
    defaults: { _controller: Magento2Bundle:Rest\Configuration:getCategoryDetails }
    methods: [GET]

magento2_list_listcategories:
    path: /magneto2-list-categories/category/parent/{categoryId}
    defaults: { _controller: magento2_pim_enrich.controller.product:listCategoriesAction, _format: json }
    requirements:
        categoryId: \d+
        
webkul_magento2_short_path_media_download:
    path: /media/webkul/download/{filename}
    defaults: { _controller: webkul.magento2.controller.rest.media:downloadShortPathAction, filter: null }
    methods: [GET]
