services:
    pim_catalog.updater.attribute:
        class: 'Akeneo\Pim\Structure\Component\Updater\AttributeUpdater'
        arguments:
            - '@pim_catalog.repository.attribute_group'
            - '@pim_catalog.repository.locale'
            - '@pim_catalog.registry.attribute_type'
            - '@pim_structure.updater.translatable'
            - ['auto_option_visual_swatch', 'auto_option_sorting', 'is_read_only']