extensions:
    webkul-magento2-credential-edit-form:
        module:  magento2/form/configuration

    webkul-magento2-credential-edit-user-navigation:
        module: pim/menu/user-navigation
        parent: webkul-magento2-credential-edit-form
        targetZone: user-menu
        config:
            userAccount: pim_menu.user.user_account
            logout: pim_menu.user.logout
    
    webkul-magento2-credential-edit-title:
        module: pim/common/grid-title
        parent: webkul-magento2-credential-edit-form
        targetZone: title
        config:
            title: magento2.edit.credential
            countable: false

    # Save Button
    webkul-magento2-credential-edit-save:
        module: magento2/form/configuration/save
        parent: webkul-magento2-credential-edit-form
        targetZone: buttons
        position: 100
        config:
            postUrl: webkul_magento2_credentials_update

    # Store Mapping
    webkul-magento2-credential-edit-store-mapping:
        module: magento2/form/configuration/tab/storeMapping
        parent: webkul-magento2-credential-edit-form
        targetZone: content
        position: 130
 
    webkul-magento2-connector-credential-edit-state:
        module: pim/form/common/state
        parent: webkul-magento2-credential-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.title
