extensions:
    webkul-magento2-connector-create-instance-modal:
        module: magento2/form/configuration/create/modal
        config:
            labels:
                title: webkul_magento2_connector.create_popin.title
                subTitle: webkul_magento2_connector.item.credential
            picture: illustrations/Groups.svg
            successMessage: webkul_magento2_credentials.message.created
            editRoute: webkul_magento2_credentials_edit
            postUrl: webkul_magento2_credentials_create

    webkul-magento2-connector-create-instance-modal-host:
        module: magento2/form/configuration/create/form
        parent: webkul-magento2-connector-create-instance-modal
        targetZone: fields
        position: 10
        config:
            labels:
                title: webkul_magento2_connector.create_popin.title
                subTitle: webkul_magento2_connector.item.export_mapping
            identifier: host
            label: webkul_magento2_connector.hostName
