services:
    # job parameters 
    webkul_magento2.job.job_parameters.product_import:
        class: 'Webkul\Magento2Bundle\JobParameters\Magento2Import'
        public: true
        arguments:
            - '@pim_catalog.repository.channel'
            - '@pim_catalog.repository.locale'            
            - [ '%webkul_magento2.job_name.all_import%' , '%webkul_magento2.job_name.attribute_import%' , '%webkul_magento2.job_name.attribute_option_import%', '%webkul_magento2.job_name.family_import%', '%webkul_magento2.job_name.product_import%', '%webkul_magento2.job_name.product_model_import%', '%webkul_magento2.job_name.category_import%', '%webkul_magento2.job_name.attribute_group_import%', '%webkul_magento2.job_name.association_import%' ]
        tags:
            - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
            - { name: akeneo_batch.job.job_parameters.default_values_provider }
