parameters:
    webkul_magento2.import_connector.name: Webkul Magento2 Akeneo Connector
    webkul_magento2.job_name.attribute_import: magento2_attribute_import
    webkul_magento2.job_name.attribute_option_import: magento2_attribute_option_import
    webkul_magento2.job_name.family_import: magento2_family_import
    webkul_magento2.job_name.product_import: magento2_product_import
    webkul_magento2.job_name.product_model_import: magento2_product_model_import
    webkul_magento2.job_name.category_import: magento2_category_import
    webkul_magento2.job_name.attribute_group_import: magento2_attribute_group_import    
    webkul_magento2.job_name.all_import: magento_2_all_import
    webkul_magento2.job_name.association_import: magento2_association_import

services:
    webkul_magento2.all_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.all_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.category.import'
                - '@webkul_magento2.step.attribute_group.import'
                - '@webkul_magento2.step.attribute.import'
                - '@webkul_magento2.step.attribute_option.import'
                - '@webkul_magento2.step.family.import'
                - '@webkul_magento2.step.root_product_model.import'
                - '@webkul_magento2.step.product.import'
                # - '@webkul.magento2.step.product_models_descendants.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }

    webkul_magento2.category_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.category_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.category.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }
    
    webkul_magento2.attribute_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.attribute_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.attribute.import'
                - '@webkul_magento2.step.attribute_option.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }            

    webkul_magento2.attribute_group_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.attribute_group_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.attribute_group.import' 
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }

    webkul_magento2.family_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.family_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.family.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }

    webkul_magento2.association_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.association_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul_magento2.step.product_model_association.import'
                - '@webkul_magento2.step.product_association.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }

    webkul_magento2.product_import:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_magento2.job_name.product_import%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                  #- '@webkul_magento2.step.root_product_model.import'
                - '@webkul_magento2.step.product.import'
                # - '@webkul.magento2.step.product_models_descendants.import'
            - true    
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.import_connector.name%', type: '%pim_connector.job.import_type%' }

