services:
    webkul_magento2.step.category.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'category_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.category_import'
            - '@pim_connector.processor.denormalization.category'
            - '@pim_connector.writer.database.category'
            - 1
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.attribute.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'attribute_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.attribute_import'
            - '@pim_connector.processor.denormalization.attribute'
            - '@pim_connector.writer.database.attribute'
            - 10
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.attribute_option.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'attribute_option_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.attribute_option_import' 
            - '@pim_connector.processor.denormalization.attribute_option'
            - '@pim_connector.writer.database.attribute_option'
            - 10
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.attribute_group.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'attribute_group_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.attribute_group_import'
            - '@pim_connector.processor.denormalization.attribute_group'
            - '@pim_connector.writer.database.attribute_group'
            - 1
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.family.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'family_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.family_import'
            - '@pim_connector.processor.denormalization.family'
            - '@pim_connector.writer.database.family'
            - 10
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.product_model_association.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'product_model_association_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.product_model_association_import'
            - '@pim_connector.processor.denormalization.product_model_association'
            - '@pim_connector.writer.database.product_model'
            - 20
            - '@?akeneo_batch.job.job_stopper'


    webkul_magento2.step.product_association.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'product_association_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.product_association_import'
            - '@pim_connector.processor.denormalization.product_association'
            - '@pim_connector.writer.database.product'
            - 20
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.root_product_model.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'import_root_product_model'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.product_model_import'
            - '@pim_connector.processor.denormalization.root_product_model'
            - '@pim_connector.writer.database.product_model'
            - 10
            - '@?akeneo_batch.job.job_stopper'

    webkul_magento2.step.product.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'product_import'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.product_import'
            - '@pim_connector.processor.denormalization.product'
            - '@pim_connector.writer.database.product'
            - 20
            - '@?akeneo_batch.job.job_stopper'

    webkul.magento2.step.product_models_descendants.import:
        class: '%webkul_magento2.export.step%'
        arguments:
            - 'import_product_model_descendants'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            - '@doctrine.orm.entity_manager'
            - '@webkul_magento2.reader.product_model_import'
            - '@pim_connector.processor.denormalization.product_model_loader'
            - '@pim_connector.writer.database.product_model_descendants'
            - 20      
            - '@?akeneo_batch.job.job_stopper'          
