services:
    webkul_magento2_association_export.job:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_mage2_association_connector.job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul.step.magento2_product_model_association_export'
                - '@webkul.step.magento2_product_association_export'
            - true
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.connector.name%', type: '%pim_connector.job.export_type%' }

    webkul_magento2_connector.quick_export_job:
        class: '%pim_connector.job.simple_job.class%'
        arguments:
            - '%webkul_mage2_product_connector.quick_export_job_name%'
            - '@event_dispatcher'
            - '@akeneo_batch.job_repository'
            -
                - '@webkul.step.magento2_credential_check.export'   
                - '@webkul.step.magento2_product.quick_export'
                - '@?webkul.step.magento2_grouped_product_link_export_quick_export'
                - '@webkul.step.magento2_product_model_association_quick_export'
                - '@webkul.step.magento2_product_association_quick_export'
                - '@?webkul.step.quick_amasty_product_attachments_export'
                - '@?webkul.step.quick_amasty_product_parts_export'
            - true
        tags:
            - { name: akeneo_batch.job, connector: '%webkul_magento2.connector.name%', type: '%pim_enrich.job.quick_export_type%' }